### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#168]
When I try to build the newest build, it throws this error at the end:

external/tinygettext/libtinygettext.so: undefined reference to `libiconv_open'
external/tinygettext/libtinygettext.so: undefined reference to `libiconv_close'
external/tinygettext/libtinygettext.so: undefined reference to `libiconv'
collect2: error: ld returned 1 exit status
make[2]: *** [supertux2] Error 1
make[1]: *** [CMakeFiles/supertux2.dir/all] Error 2
make: *** [all] Error 2

Yes, I have all submodules up-to-date.

**Comment by tobbi** [comment]
Try git clean -f, remove CMakeFiles/ directory and try again.

**Comment by brmbrmcar** [comment]
I get this (happened since CMake update):
CMake Error at CMakeLists.txt:217 (message):
  squirrel submodule is not checked out or
  /home/brmbrmcar/supertux-master/external/squirrel/CMakeLists.txt is missing

**Comment by tobbi** [comment]
brmbrmcar: git submodule update --init --recursive

**Comment by sydneyjd** [comment]
*Try git clean -f, remove CMakeFiles/ directory and try again.*

Running that fixed it. ;)

**Comment by brmbrmcar** [comment]
Still not working. I am stupid.

**Comment by Karkus476** [comment]
@brmbrmcar did you run ``cmake ..`` in your build directory?

**Comment by Karkus476** [comment]
@Hume2 Can you keep us updated? Have any of these suggestions worked?

**Comment by maths22** [comment]
@brmbrmcar Does the /home/brmbrmcar/supertux-master/external/squirrel/ directory have any files in it?

**Comment by Hume2** [comment]
I've removed everything in the build directory and builded it again.
It still throws this message.

**Comment by brmbrmcar** [comment]
@maths22 No.

**Comment by tobbi** [comment]
In that case, please try to checkout the submodule again!

**Comment by maths22** [comment]
@Hume2 What platform are you building on?

**Comment by Hume2** [comment]
@tobbi still the same message:
external/tinygettext/libtinygettext.so: undefined reference to `libiconv_open'
external/tinygettext/libtinygettext.so: undefined reference to `libiconv_close'
external/tinygettext/libtinygettext.so: undefined reference to `libiconv'
collect2: error: ld returned 1 exit status
make[2]: *** [supertux2] Error 1
make[1]: *** [CMakeFiles/supertux2.dir/all] Error 2
make: *** [all] Error 2

@maths22 I use Ubuntu 14.04.

**Comment by Hume2** [comment]
I reverted the cmke files to their current state and it works.
@tobbi , may I push that change or is there a way to hide these changes?

**Comment by tobbi** [comment]
Pull request, please. I need to review them, first.

**Comment by Hume2** [comment]
It's most likely hardware specific. If is there noone else having this problem, I'll close this.
I reverted myself the cmake files to their original state and I marked them to be not considered as changed via "git update-index --assume-unchanged <file>".

**Comment by tobbi** [comment]
It's not hardware specific. I was able to reproduce the issue on my machine... Reverting commit a549e12 fixes it.

**Comment by maths22** [comment]
I'll produce a pull request tonight that undoes the iconv stuff but keeps
the other changes.

**Comment by Mathnerd314** [comment]
It's tinygettext that's the problem, not iconv. I think https://github.com/SuperTux/tinygettext/commit/cc7fa9191268c426584bb2fb593e8f115161d65d should fix it; can someone who's getting the error test it? (I don't get it because iconv is in my glibc)

**Comment by maths22** [comment]
That is correct.  Also, that is why I do not get the error.  I meant that I
would revert the tinygettext stuff, which really is simply skirting around
the problem.

**Comment by Hume2** [comment]
Updating tinygettext throws me a strange error:
fatal: reference is not a tree: a34d942073f3e6140aff68fc325bca20f19f9b6f
Unable to checkout 'a34d942073f3e6140aff68fc325bca20f19f9b6f' in submodule path 'external/tinygettext'

So I download it from the git repository manually.

**Comment by Hume2** [comment]
@Mathnerd314 still the same error message, but thanks for your time.

**Comment by tobbi** [comment]
@Hume git submodule sync.

**Comment by tobbi** [comment]
I tried both cmake -DHAVE_SDL=ON and -DHAVE_SDL=OFF and compilation works with both.

**Comment by Hume2** [comment]
Now it woks for me. Is there anyone who still has this problem? Otherwise I'll close this.
