### ISSUE TITLE
Make the game more playable at low frames per second

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#372]
Happens to me in desktop size.

**Comment by tobbi** [comment]
Example level please.

**Comment by brmbrmcar** [comment]
OK...

**Comment by brmbrmcar** [comment]
Just try the end of Stone Cold. I cannot replicate it in my own level.

**Comment by tobbi** [comment]
My FPS counter stays on 60 almost the entire time.

**Comment by brmbrmcar** [comment]
May be my poor graphics hardware, but it only occurs in Desktop mode, and the worldmap is also laggy.

**Comment by Yoshi678** [comment]
I have to side with Tobi, Either your graphics card is bad, your processor is bad, or maybe it's just your version of SuperTux? Try running it in fullscreen.

**Comment by brmbrmcar** [comment]
My graphics hardware has been having issues in Desktop mode. Fullscreen is even worse. I think it is mainly the graphics, but they aren't *that* bad. It should be able to run SuperTux with ease.

**Comment by tobbi** [comment]
Does it make any difference if you run --renderer sdl vs. --renderer opengl?

**Comment by brmbrmcar** [comment]
It is better in opengl, but I can't really test it today...

**Comment by brmbrmcar** [comment]
OpenGL is slightly better but still has the same problems.

**Comment by sydneyjd** [comment]
This is a  GPU dependent issue. I have it on lower-resource machines that don't have decent GPUs. Its just because your GPU cannot handle higher resource intensive levels, and there is nothing that can be done about it directly. The only thing you can really do is upgrade your GPU, or even not using a resource intensive Desktop Enviroment helps as well.

**Comment by brmbrmcar** [comment]
Yes, but it can run other, more resource-dependent games, and it happens specifically with tiled cave backgrounds.

**Comment by brmbrmcar** [comment]
I think this could be more "make SuperTux more playable at low fps". It becomes very hard sometimes, and appears as a much more laggy game than it could be.

**Comment by tobbi** [comment]
eeh, didn't mean to close this. But can you please test what I just committed and tell me whether it makes any difference?

**Comment by brmbrmcar** [comment]
The nightly builds are not working, and I have not the disk space to mess with dependencies to get it compiled. And it still wouldn't really help playability, which is my main concern

**Comment by tobbi** [comment]
Nightly builds are working again: http://download.supertuxproject.org/download/

**Comment by brmbrmcar** [comment]
They still do not work for me. I cannot install Wine.

**Comment by brmbrmcar** [comment]
6cf567a did not fix anything. In fact, I believe it may be doing the opposite...

**Comment by brmbrmcar** [comment]
Interestingly, small Tux is much worse for this...

**Comment by tobbi** [comment]
This will possibly be fixed some later time, when we replace the older OpenGL calls with some newer OpenGL calls.

**Comment by Hume2** [comment]
Also do you want more fps or make it more playable at low fps? This is quite different. When the fps is low, the gamespeed decreases, making it more playable. Or would you like to see glitching-trough-walls bugs instead?

**Comment by brmbrmcar** [comment]
No, on other games at low fps I just see flickering of the game. That is all that needs to happen. I've tried much more resource-heavy games like Minecraft and it has been much more playable despite low fps. It is easily possible!

**Comment by brmbrmcar** [comment]
didn't even have a gpu lol

**Comment by brmbrmcar** [comment]
It is definitely possible. Whilst using some trick to limit the fps through some glinject trick it runs far smoother, even when FPS is lowered. If there was a way to limit FPS automatically, or hell even as an option, it would make it far more playable.

**Comment by tobbi** [comment]
@brmbrmcar Can this issue be closed? Is the game playable at lower fps now?

**Comment by brmbrmcar** [comment]
I'm pretty much unable to test because my system is completely different now. I could try and install master and emulate low fps caused by low performance.

**Comment by tobbi** [comment]
@brmbrmcar Try that, please.

**Comment by HybridDog** [comment]
When I increase the time speed in the debug menu to make supertux run e.g. 4 times faster, Tux can no longer jump correctly and I cannot jump over enemies.

**Comment by HybridDog** [comment]
The FPS shown in supertux are wrong: the real framerate often is lower.
If `SDL_GetTicks() - fps_ticks` is 700, `fps_ticks` is still set to `SDL_GetTicks()` and not `SDL_GetTicks() + 200`, i.e. remaining milliseconds are discarded.
https://github.com/SuperTux/supertux/blob/4e3786d9c2fbcfebee372977408effe969cced4a/src/supertux/screen_manager.cpp#L200-L205

**Comment by tobbi** [comment]
@brmbrmcar Can this be closed?

**Comment by tobbi** [comment]
I'm going to close this due to lack of response. It can get reopened should the issue still persist.

**Comment by henriqueneves5** [comment]
The graphics in my game are bad
